### ISSUE TITLE
Cant' install `sphinxcontrib-openapi` with latest version of sphinx and pipenv

### ISSUE THREAD

**Issue by monkut** [sphinx-contrib/openapi#121]
Trying to install with the latest version of Sphinx via pipenv.

Pipfile:

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
sphinx = "*"
sphinxcontrib-seqdiag = "*"
#sphinxcontrib-openapi = "*
sphinxcontrib-blockdiag = "*"
funcparserlib= ">=1.0.0a0"

[requires]
python_version = "3.9"

[pipenv]
allow_prereleases = true
```

Installation Error:
```
Installing initially failed dependencies...
[InstallError]:   File "/home/shane/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pipenv/cli/command.py", line 233, in install
[InstallError]:       retcode = do_install(
[InstallError]:   File "/home/shane/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pipenv/core.py", line 2052, in do_install
[InstallError]:       do_init(
[InstallError]:   File "/home/shane/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pipenv/core.py", line 1304, in do_init
[InstallError]:       do_install_dependencies(
[InstallError]:   File "/home/shane/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pipenv/core.py", line 899, in do_install_dependencies
[InstallError]:       batch_install(
[InstallError]:   File "/home/shane/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pipenv/core.py", line 796, in batch_install
[InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
[InstallError]:   File "/home/shane/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pipenv/core.py", line 703, in _cleanup_procs
[InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: Collecting m2r==0.2.1
[pipenv.exceptions.InstallError]:   Using cached m2r-0.2.1.tar.gz (16 kB)
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'error'
[pipenv.exceptions.InstallError]:   ERROR: Command errored out with exit status 1:
[pipenv.exceptions.InstallError]:    command: /home/shane/.local/share/virtualenvs/kobashi-specifications-_0DhKfNE/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g1vgu8_u/m2r_f0b1c08b729f43fb86793ad8df0ab045/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g1vgu8_u/m2r_f0b1c08b729f43fb86793ad8df0ab045/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-osly6xvj
[pipenv.exceptions.InstallError]:        cwd: /tmp/pip-install-g1vgu8_u/m2r_f0b1c08b729f43fb86793ad8df0ab045/
[pipenv.exceptions.InstallError]:   Complete output (7 lines):
[pipenv.exceptions.InstallError]:   Traceback (most recent call last):
[pipenv.exceptions.InstallError]:     File "<string>", line 1, in <module>
[pipenv.exceptions.InstallError]:     File "/tmp/pip-install-g1vgu8_u/m2r_f0b1c08b729f43fb86793ad8df0ab045/setup.py", line 14, in <module>
[pipenv.exceptions.InstallError]:       from m2r import parse_from_file
[pipenv.exceptions.InstallError]:     File "/tmp/pip-install-g1vgu8_u/m2r_f0b1c08b729f43fb86793ad8df0ab045/m2r.py", line 59, in <module>
[pipenv.exceptions.InstallError]:       class RestBlockGrammar(mistune.BlockGrammar):
[pipenv.exceptions.InstallError]:   AttributeError: module 'mistune' has no attribute 'BlockGrammar'
[pipenv.exceptions.InstallError]:   ----------------------------------------
[pipenv.exceptions.InstallError]: WARNING: Discarding https://files.pythonhosted.org/packages/39/e7/9fae11a45f5e1a3a21d8a98d02948e597c4afd7848a0dbe1a1ebd235f13e/m2r-0.2.1.tar.gz#sha256=bf90bad66cda1164b17e5ba4a037806d2443f2a4d5ddc9f6a5554a0322aaed99 (from https://pypi.org/simple/m2r/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement m2r==0.2.1 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.2.0, 0.2.1)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for m2r==0.2.1
ERROR: Couldn't install package: m2r
```

**Comment by sevdog** [comment]
I am getting a similar error due to mistune 2.x in which `BlockGrammar` was removed from the codebase.
